LogOutputStream.create(LineConsumer)
zeroturnaround/zt-exec pull request #107
Opened 2023-03-03 17:53 UTC by panchenko

So instead of creating an anonymous class it can be one-liner with lambda expression.

2023-03-03 17:59 UTC, panchenko commented
If we are going to proceed with this, then I can also add an example to the readme file.

2023-03-03 21:24 UTC, nemecec requested changes
Cool idea, thanks! I think the JavaDoc could be better (I added some comments with suggestions, feel free to use those as inspiration).
Also, a unit test and example usage in README would be much appreciated.

2023-03-03 21:24 UTC, nemecec commented on src/main/java/org/zeroturnaround/exec/stream/LogOutputStream.java
> +   */
```suggestion
  /**
   * This is equivalent to {@code java.util.function.Consumer} while staying compatible with
   * Java versions earlier than 8.
   */
```

2023-03-03 21:24 UTC, nemecec commented on src/main/java/org/zeroturnaround/exec/stream/LogOutputStream.java
> +   */
```suggestion
  /**
  * Factory method to create a <code>LogOutputStream</code> that passes each line to the specified consumer.
  * <p>Mostly useful with Java 8+, so the consumer can be passed as a lambda expression.</p>
  *
  * @param consumer the consumer to consume the log lines
   * @return the created <code>LogOutputStream</code>, passing each line to the specified consumer.
   */
```

2023-03-04 07:24 UTC, panchenko commented on README.md
> +    .redirectOutput(LogOutputStream.create(line -> ...))
Theoretically, there could be also a new method here `.processOutput(line -> ...)`, WDYT?

2023-03-24 17:13 UTC, aalmiray commented
Bytecode compatibility is set to Java 6 as a minimum which will prevent the use of lambdas.
I'd suggest bumping to 7 as a minimum as JDK 17 (see PR for build) fails if 6 is chosen.
Another option would be to bump to Java 8 as a minimum, in which case lambdas may be used.

Bear in mind that bumping Java baseline constitutes a breaking change and thus the library should increase its major version number according to semver.

2023-05-04 15:39 UTC, panchenko commented
@nemecec Could you lease take a look? Thanks!

2024-03-14 16:12 UTC, panchenko commented
Is this project maintained?

2024-03-15 20:26 UTC, nemecec commented
> Is this project maintained?

Sorry, I totally forgot about this PR. Looks good, I'll merge it in.

2024-03-15 20:27 UTC, merged

2024-03-15 20:28 UTC, nemecec commented
Thanks for the PR!